import os

SECRET_KEY = "<SECRET_KEY_HERE>"
GOOGLE_OAUTH_CLIENT_ID = "<GOOGLE_OAUTH_CLIENT_ID_HERE>"
GOOGLE_OAUTH_CLIENT_SECRET = "<GOOGLE_OAUTH_CLIENT_SECRET_HERE>"
OPENAI_API_KEY = "<OPENAI_API_KEY_HERE>"


os.environ["SECRET_KEY"] = SECRET_KEY
os.environ["GOOGLE_CLIENT_ID"] = GOOGLE_OAUTH_CLIENT_ID
os.environ["GOOGLE_CLIENT_SECRET"] = GOOGLE_OAUTH_CLIENT_SECRET
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY